name: "Lint check"

on:
  pull_request:
    branches: [ main, development ]
    types: [ opened, synchronize, reopened ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goldenm-software/python-builder:3.11
      options: --user root
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dev dependencies
        run: |
          pip3 install -U -r requirements-dev.txt

      - name: Lint
        run: |
          ruff check
